site_name: "Insights by Groosg"
site_description: "Software development insights by Groosg: tutorials, guides, tips, etc."
site_author: "Groosg"
site_url: "https://groosg.github.io/insights"

repo_name: "groosg/insights"
repo_url: "https://github.com/groosg/insights"
edit_uri: "edit/main/docs/"

copyright: Copyright &copy; 2022 Groosg

extra_css:
  - assets/stylesheets/extra.css

theme:
  name: "material"
  custom_dir: theme
  icon:
    repo: fontawesome/brands/github

  language: en
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: green
      accent: green
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/groosg
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gr00sg
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  card:
    twitter: "@gr00sg"
    image_url: assets/images/twitter_card.png
    type: summary

plugins:
  - search
  - git-revision-date-localized:
      type: timeago # date, datetime, iso_date, iso_datetime, timeago
      enable_creation_date: false
      fallback_to_build_date: false

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - footnotes

nav:
  - Home:
    - Home: index.md
  - Tips:
    - GitHub Account Setup: tips/gh_setup.md